2024-06-17 17:36:57,629 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-06-17 17:36:57,629 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Configure stats pid to 3818
2024-06-17 17:36:57,629 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Loading settings from /home/ali/.config/wandb/settings
2024-06-17 17:36:57,629 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Loading settings from /home/ali/tum/i2dl/exercise/i2dl/exercise_09/wandb/settings
2024-06-17 17:36:57,629 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-17 17:36:57,630 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-17 17:36:57,630 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-06-17 17:36:57,630 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-17 17:36:57,630 INFO    MainThread:3818 [wandb_init.py:_log_setup():520] Logging user logs to /home/ali/tum/i2dl/exercise/i2dl/exercise_09/wandb/run-20240617_173657-ys7gect3/logs/debug.log
2024-06-17 17:36:57,630 INFO    MainThread:3818 [wandb_init.py:_log_setup():521] Logging internal logs to /home/ali/tum/i2dl/exercise/i2dl/exercise_09/wandb/run-20240617_173657-ys7gect3/logs/debug-internal.log
2024-06-17 17:36:57,630 INFO    MainThread:3818 [wandb_init.py:init():560] calling init triggers
2024-06-17 17:36:57,630 INFO    MainThread:3818 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'hidden_dim': 1, 'num_hidden_linear': 50, 'epochs': 3, 'batchsize': 40, 'learning_rate': 0.0001}
2024-06-17 17:36:57,630 INFO    MainThread:3818 [wandb_init.py:init():585] re-initializing run, found existing run on stack: dojiynlp
2024-06-17 17:36:57,631 INFO    MainThread:3818 [wandb_run.py:_finish():2109] finishing run alfreds-organization/my-awesome-project/dojiynlp
2024-06-17 17:36:57,632 ERROR   MainThread:3818 [jupyter.py:save_history():436] Run pip install nbformat to save notebook history
2024-06-17 17:36:57,632 INFO    MainThread:3818 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-06-17 17:36:57,632 INFO    MainThread:3818 [wandb_init.py:_jupyter_teardown():448] cleaning up jupyter logic
2024-06-17 17:36:57,632 INFO    MainThread:3818 [wandb_run.py:_atexit_cleanup():2349] got exitcode: 0
2024-06-17 17:36:57,632 INFO    MainThread:3818 [wandb_run.py:_restore():2332] restore
2024-06-17 17:36:57,632 INFO    MainThread:3818 [wandb_run.py:_restore():2338] restore done
2024-06-17 17:37:02,333 INFO    MainThread:3818 [wandb_run.py:_footer_history_summary_info():4008] rendering history
2024-06-17 17:37:02,334 INFO    MainThread:3818 [wandb_run.py:_footer_history_summary_info():4040] rendering summary
2024-06-17 17:37:02,338 INFO    MainThread:3818 [wandb_run.py:_footer_sync_info():3967] logging synced files
2024-06-17 17:37:02,359 INFO    MainThread:3818 [wandb_init.py:init():610] starting backend
2024-06-17 17:37:02,359 INFO    MainThread:3818 [wandb_init.py:init():614] setting up manager
2024-06-17 17:37:02,362 INFO    MainThread:3818 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-17 17:37:02,362 INFO    MainThread:3818 [wandb_init.py:init():622] backend started and connected
2024-06-17 17:37:02,364 INFO    MainThread:3818 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-06-17 17:37:02,364 INFO    MainThread:3818 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-06-17 17:37:02,364 INFO    MainThread:3818 [wandb_init.py:init():711] updated telemetry
2024-06-17 17:37:02,366 INFO    MainThread:3818 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-17 17:37:03,891 INFO    MainThread:3818 [wandb_run.py:_on_init():2402] communicating current version
2024-06-17 17:37:03,971 INFO    MainThread:3818 [wandb_run.py:_on_init():2411] got version response 
2024-06-17 17:37:03,971 INFO    MainThread:3818 [wandb_init.py:init():795] starting run threads in backend
2024-06-17 17:37:05,607 INFO    MainThread:3818 [wandb_run.py:_console_start():2380] atexit reg
2024-06-17 17:37:05,608 INFO    MainThread:3818 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2024-06-17 17:37:05,608 INFO    MainThread:3818 [wandb_run.py:_redirect():2300] Wrapping output streams.
2024-06-17 17:37:05,608 INFO    MainThread:3818 [wandb_run.py:_redirect():2325] Redirects installed.
2024-06-17 17:37:05,608 INFO    MainThread:3818 [wandb_init.py:init():838] run started, returning control to user process
2024-06-17 17:37:14,411 WARNING MsgRouterThr:3818 [router.py:message_loop():77] message_loop has been closed
2024-06-17 17:38:02,212 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-06-17 17:38:02,212 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Configure stats pid to 3818
2024-06-17 17:38:02,212 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Loading settings from /home/ali/.config/wandb/settings
2024-06-17 17:38:02,212 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Loading settings from /home/ali/tum/i2dl/exercise/i2dl/exercise_09/wandb/settings
2024-06-17 17:38:02,212 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-17 17:38:02,212 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-17 17:38:02,212 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-06-17 17:38:02,212 INFO    MainThread:3818 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-17 17:38:02,213 INFO    MainThread:3818 [wandb_init.py:_log_setup():520] Logging user logs to /home/ali/tum/i2dl/exercise/i2dl/exercise_09/wandb/run-20240617_173802-fixof9j8/logs/debug.log
2024-06-17 17:38:02,213 INFO    MainThread:3818 [wandb_init.py:_log_setup():521] Logging internal logs to /home/ali/tum/i2dl/exercise/i2dl/exercise_09/wandb/run-20240617_173802-fixof9j8/logs/debug-internal.log
2024-06-17 17:38:02,213 INFO    MainThread:3818 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7e0707ed5f90>
2024-06-17 17:38:02,213 INFO    MainThread:3818 [wandb_init.py:init():560] calling init triggers
2024-06-17 17:38:02,213 INFO    MainThread:3818 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'hidden_dim': 1, 'num_hidden_linear': 50, 'epochs': 3, 'batchsize': 40, 'learning_rate': 0.0001}
2024-06-17 17:38:02,213 INFO    MainThread:3818 [wandb_init.py:init():585] re-initializing run, found existing run on stack: ys7gect3
2024-06-17 17:38:02,214 ERROR   MainThread:3818 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 595, in init
    latest_run.finish()
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 390, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2100, in finish
    return self._finish(exit_code, quiet)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2107, in _finish
    with telemetry.context(run=self) as tel:
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 798, in _telemetry_callback
    self._telemetry_flush()
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 809, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2024-06-17 17:38:04,384 ERROR   MainThread:3818 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    wi.setup(kwargs)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 219, in setup
    with telemetry.context(obj=self._init_telemetry_obj) as tel:
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 798, in _telemetry_callback
    self._telemetry_flush()
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 809, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2024-06-17 17:38:09,346 ERROR   MainThread:3818 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    wi.setup(kwargs)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 219, in setup
    with telemetry.context(obj=self._init_telemetry_obj) as tel:
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 798, in _telemetry_callback
    self._telemetry_flush()
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 809, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/ali/miniconda3/envs/i2dl/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
